name: ScreenShotMaker
options:
  bundleIdPrefix: com.fromkk
  deploymentTarget:
    macOS: "15.0"
  xcodeVersion: "16.0"
  minimumXcodeGenVersion: "2.0"

settings:
  base:
    SWIFT_VERSION: "6.0"
    MACOSX_DEPLOYMENT_TARGET: "15.0"

targets:
  ScreenShotMaker:
    type: application
    platform: macOS
    sources:
      - path: ScreenShotMaker
        excludes:
          - "**/*.xcassets"
    resources:
      - path: ScreenShotMaker/Resources/Assets.xcassets
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.fromkk.ScreenShotMaker
        PRODUCT_NAME: ScreenShotMaker
        INFOPLIST_KEY_LSApplicationCategoryType: "public.app-category.graphics-design"
        INFOPLIST_KEY_CFBundleDisplayName: ScreenShotMaker
        CODE_SIGN_ENTITLEMENTS: ScreenShotMaker/ScreenShotMaker.entitlements
        GENERATE_INFOPLIST_FILE: YES
        MARKETING_VERSION: "1.0.0"
        CURRENT_PROJECT_VERSION: "1"
        SWIFT_STRICT_CONCURRENCY: complete
    entitlements:
      path: ScreenShotMaker/ScreenShotMaker.entitlements
